unicode: Allow building kunit test suite as a module
Starting on commit c475c77d5b56 ("kunit: allow kunit tests to be loaded
as a module") kunit testsuites need to be buildable as modules, to
prevent the undefined references below, in case KUNIT itself was made a
module:

utf8-test.c:(.text+0x48): undefined reference to `kunit_ptr_not_err_assert_format'
>> sparc64-linux-ld: utf8-test.c:(.text+0x50): undefined reference to `kunit_ptr_not_err_assert_format'
>> sparc64-linux-ld: utf8-test.c:(.text+0xb4): undefined reference to `kunit_do_assertion'
>> sparc64-linux-ld: utf8-test.c:(.text+0xbc): undefined reference to
`kunit_binary_assert_format'

This was found by 0-day on linux-next and fixes the allmodconfig build

CC: Ricardo Cañuelo <ricardo.canuelo@collabora.com>
Fixes: d269543a1dcb ("unicode: implement utf8 unit tests as a KUnit test suite")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Gabriel Krisman Bertazi <krisman@collabora.com>